# ConfigMap for Production environment
apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-service-config
  namespace: resume-prod
  labels:
    app: resume-service
    environment: production
data:
  # Spring Boot Configuration
  SPRING_PROFILES_ACTIVE: "prod,kubernetes"
  SERVER_PORT: "8080"
  
  # Environment-specific settings
  ENVIRONMENT: "production"
  LOG_LEVEL: "WARN"
  
  # Database settings (if needed)
  DB_HOST: "prod-db-host"
  DB_PORT: "5432"
  DB_NAME: "resume_service_prod"
  
  # Application settings
  APP_NAME: "Resume Service - Production"
  APP_VERSION: "1.0.0"
  
  # Monitoring and observability
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"
  
  # JVM settings for production environment
  JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
  
  # External service URLs (production environment)
  EXTERNAL_API_URL: "https://api.example.com"
  
  # Feature flags
  FEATURE_NEW_API: "false"
  FEATURE_ENHANCED_LOGGING: "false"
  
  # Security settings
  SECURITY_REQUIRE_SSL: "true"
  CORS_ALLOWED_ORIGINS: "https://yourdomain.com"
