# automation/k8s/manifests/config_map/prod.yaml - ADD namespace
apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-service-config
  namespace: prod                      # ← ADD THIS
  labels:
    app: resume-service
    environment: production
data:
  SPRING_PROFILES_ACTIVE: "prod"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  APP_NAME: "Resume Service - Production"