# config_map/test.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-service-config
  labels:
    app: resume-service
    environment: test
data:
  SPRING_PROFILES_ACTIVE: "test"
  ENVIRONMENT: "test"
  LOG_LEVEL: "DEBUG"
  APP_NAME: "Resume Service - Test"