name: Resume-Service-CI

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - app_svc/src/*
    - app_svc/DockerFile
    - automation/*

variables:
  dockerRegistryServiceConnection: 'acr-service-connection'
  imageRepository: 'resume-service'
  containerRegistry: 'amoshacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app_svc/DockerFile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

  - job: PublishTerraform
    displayName: 'Publish Terraform'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Terraform Artifacts'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/automation/iac'
        artifact: 'terraform-artifacts'

  - job: PublishK8s
    displayName: 'Publish K8s'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish K8s Manifests'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/automation/k8s'
        artifact: 'k8s-artifacts'