apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-service-deployment
  namespace: ${NAMESPACE}              
  labels:
    app: resume-service
    environment: ${ENVIRONMENT}        
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-service
  template:
    metadata:
      labels:
        app: resume-service
        environment: ${ENVIRONMENT}
    spec:
      containers:
      - name: resume-service
        image: amoshacr.azurecr.io/resume-service:${BUILD_ID}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: resume-service-config
      imagePullSecrets:
      - name: acr-auth