apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: resume-service-rs
  labels:
    app: resume-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-service
  template:
    metadata:
      labels:
        app: resume-service
    spec:
      containers:
      - name: resume-service
        image: amoshacr.azurecr.io/resume-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"