apiVersion: v1
kind: Service
metadata:
  name: resume-service-lb
  labels:
    app: resume-service
spec:
  type: LoadBalancer
  selector:
    app: resume-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
