apiVersion: v1
kind: Service
metadata:
  name: resume-service-lb
  labels:
    app: resume-service
spec:
  type: LoadBalancer
  selector:
    app: resume-service
  ports:
  - port: 8080
    targetPort: 8080