apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-service
spec:
  template:
    spec:
      containers:
      - name: resume-service
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
